---
- name: Install and configure ClickHouse
  hosts: servers
  become: yes
  vars:
    clickhouse_version: "24.8"  # Specify desired version
    clickhouse_password: "ZoNq3hHlglto7qc"  # Change this to a secure password
  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - dirmngr
        state: present
        update_cache: yes

    - name: Import ClickHouse GPG key
      ansible.builtin.command:
        cmd: gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754
        creates: /usr/share/keyrings/clickhouse-keyring.gpg
      args:
        warn: no  # Suppress warning about using command module

    - name: Add ClickHouse repository
      ansible.builtin.shell:
        cmd: echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main" | tee /etc/apt/sources.list.d/clickhouse.list
        creates: /etc/apt/sources.list.d/clickhouse.list
      args:
        warn: no  # Suppress warning about using shell module

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install ClickHouse packages
      ansible.builtin.apt:
        name:
          - clickhouse-server
          - clickhouse-client
        state: present

    - name: Ensure ClickHouse configuration directory exists
      ansible.builtin.file:
        path: /etc/clickhouse-server
        state: directory
        mode: '0755'

    - name: Configure ClickHouse to listen on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/clickhouse-server/config.xml
        regexp: '<!-- <listen_host>0.0.0.0</listen_host> -->'
        line: '<listen_host>0.0.0.0</listen_host>'
        backup: yes
      notify: Restart ClickHouse

    - name: Create users configuration file
      ansible.builtin.copy:
        content: |
          <clickhouse>
            <users>
              <default>
                <password_sha256_hex>{{ clickhouse_password | hash('sha256') }}</password_sha256_hex>
                <access_management>1</access_management>
                <networks>
                  <ip>::/0</ip>
                </networks>
              </default>
            </users>
          </clickhouse>
        dest: /etc/clickhouse-server/users.d/default-password.xml
        mode: '0644'
      notify: Restart ClickHouse

    - name: Ensure ClickHouse service is started and enabled
      ansible.builtin.service:
        name: clickhouse-server
        state: started
        enabled: yes

  handlers:
    - name: Restart ClickHouse
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
