---
- name: Install and configure ClickHouse
  hosts: servers
  become: yes
  vars:
    clickhouse_version: "24.8"  # Specify desired version
    clickhouse_password: "ZoNq3hHlglto7qc"  # Change this to a secure password
  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Download and dearmor ClickHouse GPG key
      ansible.builtin.shell:
        cmd: curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | gpg --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg
        creates: /usr/share/keyrings/clickhouse-keyring.gpg
      register: gpg_result
      changed_when: gpg_result.rc == 0

    - name: Get system architecture
      ansible.builtin.command:
        cmd: dpkg --print-architecture
      register: arch_result
      changed_when: false

    - name: Add ClickHouse repository
      ansible.builtin.shell:
        cmd: echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg arch={{ arch_result.stdout }}] https://packages.clickhouse.com/deb stable main" | tee /etc/apt/sources.list.d/clickhouse.list
        creates: /etc/apt/sources.list.d/clickhouse.list
      register: repo_result
      changed_when: repo_result.rc == 0

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install ClickHouse packages
      ansible.builtin.apt:
        name:
          - clickhouse-server
          - clickhouse-client
        state: present

    - name: Ensure ClickHouse configuration directory exists
      ansible.builtin.file:
        path: /etc/clickhouse-server
        state: directory
        mode: '0755'

    - name: Configure ClickHouse to listen on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/clickhouse-server/config.xml
        regexp: '<!-- <listen_host>0.0.0.0</listen_host> -->'
        line: '<listen_host>0.0.0.0</listen_host>'
        backup: yes
      notify: Restart ClickHouse

    - name: Configure default user password in users.xml
      ansible.builtin.blockinfile:
        path: /etc/clickhouse-server/users.xml
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        insertafter: "<default>"
        block: |
          <password>ZoNq3hHlglto7qc</password>
          <access_management>1</access_management>
          <networks>
            <ip>::/0</ip>
          </networks>
        backup: yes
      notify: Restart ClickHouse

    - name: Ensure ClickHouse service is started and enabled
      ansible.builtin.service:
        name: clickhouse-server
        state: started
        enabled: yes

  handlers:
    - name: Restart ClickHouse
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
