---
- name: Change Username
  hosts: all
  become: yes
  vars:
    old_username: "test"
    new_username: "newuser"

  tasks:
    - name: Ensure the new user exists
      user:
        name: "{{ new_username }}"
        state: present
        groups: "{{ lookup('config', 'new_user_groups', default='sudo') }}"
        append: yes

    - name: Transfer home directory to the new user
      command: >
        rsync -a /home/{{ old_username }}/ /home/{{ new_username }}/
      when: ansible_facts['ansible_user_id'] != new_username

    - name: Update the ownership of the new home directory
      file:
        path: /home/{{ new_username }}
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        recurse: yes

    - name: Remove the old user
      user:
        name: "{{ old_username }}"
        state: absent
        remove: yes
      when: ansible_facts['ansible_user_id'] != old_username
