---
- name: create user and add to sudo
  hosts: all
  become: true
  tasks:
    
    - name: Create user
      user:
        name: m2sdev
        password: "{{ 'm2sdev@123#' | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes

    - name: Add user to sudoers group
      user:
        name: m2sdev
        groups: sudo
        append: yes
