---
- name: Install Telegraf and InfluxDB and configure Telegraf to send metrics to InfluxDB
  hosts: all
  become: true
  vars:   
    telegraf_version: "latest"   

  tasks:
  
    - name: install updates (Ubuntu)
    tags: always
    apt:
       upgrade: dist
       update_cache: yes
  
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - curl  

    - name: Install Telegraf
      apt:
        name: telegraf
        state: present

    - name: Configure Telegraf
      template:
        src: telegraf.conf.j2
        dest: /etc/telegraf/telegraf.conf
      notify: restart telegraf

  handlers:
    - name: restart telegraf
      service:
        name: telegraf
        state: restarted
