- name: update, time, hostname
  hosts: all
  become: true
  tasks:
    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes   
  
    - name: Set timezone to Asia/Dhaka
      timezone:
        name: Asia/Dhaka

    - name: Set hostname
      hostname:
        name: maradb-n1
