- name: User Management Playbook
  hosts: all
  become: yes
  vars:
    user_to_delete: test
    new_user: newuser
    new_user_password: 1

  tasks:
    - name: Ensure the old user is absent
      user:
        name: "{{ user_to_delete }}"
        state: absent

    - name: Create a new user
      user:
        name: "{{ new_user }}"
        password: "{{ new_user_password | password_hash('sha512') }}"
        state: present
        shell: /bin/bash

    - name: Add the new user to the sudo group
      user:
        name: "{{ new_user }}"
        groups: sudo
        append: yes
