---
- name: Set up UFW with custom rules
  hosts: all
  become: yes
  tasks:
    - name: Apply kernel tuning parameters
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { key: 'fs.file-max', value: '4194303' }
        - { key: 'vm.swappiness', value: '1' }
        - { key: 'vm.vfs_cache_pressure', value: '10' }
        - { key: 'vm.min_free_kbytes', value: '1000000' }
        - { key: 'net.core.rmem_max', value: '268435456' }
        - { key: 'net.core.wmem_max', value: '268435456' }
        - { key: 'net.core.rmem_default', value: '67108864' }
        - { key: 'net.core.wmem_default', value: '67108864' }
        - { key: 'net.core.netdev_budget', value: '1200' }
        - { key: 'net.core.optmem_max', value: '134217728' }
        - { key: 'net.core.somaxconn', value: '65535' }
        - { key: 'net.core.netdev_max_backlog', value: '250000' }
        - { key: 'net.ipv4.tcp_rmem', value: '67108864 134217728 268435456' }
        - { key: 'net.ipv4.tcp_wmem', value: '67108864 134217728 268435456' }
        - { key: 'net.ipv4.tcp_low_latency', value: '1' }
        - { key: 'net.ipv4.tcp_adv_win_scale', value: '1' }
        - { key: 'net.ipv4.tcp_max_syn_backlog', value: '30000' }
        - { key: 'net.ipv4.tcp_max_tw_buckets', value: '2000000' }
        - { key: 'net.ipv4.tcp_tw_reuse', value: '1' }
        - { key: 'net.ipv4.tcp_fin_timeout', value: '5' }
        - { key: 'net.ipv4.conf.all.send_redirects', value: '0' }
        - { key: 'net.ipv4.conf.all.accept_redirects', value: '0' }
        - { key: 'net.ipv4.conf.all.accept_source_route', value: '0' }
        - { key: 'net.ipv4.tcp_mtu_probing', value: '1' }
        - { key: 'vm.overcommit_memory', value: '1' }
