---
- name: Set up UFW with custom rules
  hosts: all
  become: yes
  tasks:
    # Update apt cache and upgrade the system
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Keeps the cache for 1 hour

    - name: Upgrade all apt packages
      apt:
        upgrade: yes
        autoclean: yes
        autoremove: yes
