---
- name: Set up UFW with custom rules
  hosts: all
  become: yes
  tasks:
    - name: Install necessary tools
      apt:
        name:
          - traceroute
          - curl
          - wget
          - net-tools   # for netstat
          - btop
          - ncdu
          - speedtest-cli
          - fio
        state: present
        update_cache: yes
