---
- name: Install Telegraf
  hosts: all
  become: true   

  tasks:
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - curl  

    - name: Install Telegraf
      apt:
        name: telegraf
        state: present

    - name: Configure Telegraf
      template:
        src: telegraf.conf.j2
        dest: /etc/telegraf/telegraf.conf
      notify: restart telegraf

  handlers:
    - name: restart telegraf
      service:
        name: telegraf
        state: restarted
